# Generated by Django 3.2.7 on 2021-09-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capabilities',
            fields=[
                ('CAP_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name_of_capability', models.CharField(max_length=255)),
                ('description_of_capability', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('TEMP_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name_of_template', models.CharField(max_length=255)),
                ('capabilities', models.ManyToManyField(to='templ.Capabilities')),
            ],
        ),
    ]
